### ISSUE TITLE
E/GeckoLibLoad: Couldn't get a handle to libnss3! error after updating to Android Studio 3.6

### ISSUE THREAD

**Issue by acrolink** [mozilla/geckoview#116]
My application fails to start with the error message:

`E/GeckoLibLoad: Couldn't get a handle to libnss3!`

and:

```
java.lang.Exception: Error loading sqlite libraries
        at org.mozilla.gecko.mozglue.GeckoLoader.loadSQLiteLibsNative(Native Method)
        at org.mozilla.gecko.mozglue.GeckoLoader.loadSQLiteLibs(GeckoLoader.java:200)
        at org.mozilla.gecko.GeckoThread.loadGeckoLibs(GeckoThread.java:269)
        at org.mozilla.gecko.GeckoThread.initGeckoEnvironment(GeckoThread.java:289)
        at org.mozilla.gecko.GeckoThread.run(GeckoThread.java:448)
```

Seeing this issue after updating to Android Studio 3.6 from 3.5.

*IMPORTANT*

caused by using Gradle Plugin 3.6.0, switching back to 3.5.3 solves the issue.

**Comment by artroman** [comment]
> caused by using Gradle Plugin 3.6.0, switching back to 3.5.3 solves the issue.

Changing gradle plugin from 3.6.0 to 3.5.3 doesn't fixes the issue. Updated Studio (gradle plugin 3.6.1) also fails to run.

I have found the cause My code and libraries loads native libraries using System.loadLibrary(), so I have added android:extractNativeLibs="false" in AndroidManifest to save storage space and speed up application install/update process. But GeckView doesn't load libnss3 via GeckoLoader, it loads library from native code, so *.so files should be prepared (extracted) to app's local libs folder. 

Changing Manifest extractNativeLibs from "false" to "true" fixes the issue for me. By the way, installed App size increased from 127 MB to 170 MB in x86 emulator (build for this arch only).

**Comment by snorp** [comment]
Yeah, we don't support `extractNativeLibs=false` yet. It's coming. You can track this for updates: https://bugzilla.mozilla.org/show_bug.cgi?id=1610018

**Comment by acrolink** [comment]
Adding `extractNativeLibs=true` to `AndroidManifest` resolves the issue.

**Comment by ddsc01** [comment]
This issue also appears when building with gradle Version 3.6.1. 
You need to have android.bundle.enableUncompressedNativeLibs=false in gradle.properties and android:extractNativeLibs="true" in AndroidManifest to make it work. If you use Gradle 3.5.3 you don't need those entries.

**Comment by artroman** [comment]
> Yeah, we don't support `extractNativeLibs=false` yet. It's coming. You can track this for updates: https://bugzilla.mozilla.org/show_bug.cgi?id=1610018

It was changed
```
Resolution: --- → FIXED
Target Milestone: --- → mozilla76
```

But GeckoView 76.0 (available in nightly) still crashes with extractNativeLibs="false". Tested  latest available version "geckoview-nightly:76.0.20200406092400".

**Comment by Cilenco** [comment]
Also getting this for version _64.0.20190125143600_ and gradle plugin 3.6.2.
Setting `android:extractNativeLibs="true"` did not help.

It's the only version which does not expend my apk size to over 100 MB

**Comment by artroman** [comment]
> Also getting this for version _64.0.20190125143600_ and gradle plugin 3.6.2.

I can't find this version as default "geckoview" artifact: https://maven.mozilla.org/?prefix=maven2/org/mozilla/geckoview/geckoview/
The oldest one available is 69.0.20190903125908.

Do you use platform-specific artifact, such as geckoview-armeabi-v7a? This will work on mobile, but fail on emulator because native libraries are missing in apk for this architecture (x86 or x86_64). 

You should use universal artifact to get all native libraries. Then add abi filters to get smaller apk size or use App Bundles or APK Splits:
```
ndk {
    abiFilters "armeabi-v7a", "x86"
}
```
This produces 89 MB debug apk for geckoview 69.

More on android documentation: https://developer.android.com/ndk/guides/abis#gc

**Comment by snorp** [comment]
This should be working now with latest geckoview.

**Comment by widevel** [comment]
> This should be working now with latest geckoview.

Still not working in 80.0.20200903001900 stable version

**Comment by s-ankur** [comment]
I am also having the same issue

**Comment by bapidas1** [comment]
@snorp This issue is still there. It's not fixed yet.

**Comment by daarong** [comment]
Still an issue on 90.0.20210705185941
Gradle Plugin 4.2.2, gradle version 6.7.1

The suggestion here did it for me -- https://bugzilla.mozilla.org/show_bug.cgi?id=1571175

Add this to gradle.properties
android.bundle.enableUncompressedNativeLibs=false

-----------------------------------------------------------------------------------------------

Very confusing for me because this error does NOT show when testing in Android Studio. And I'm an Android noob.

NO error in these cases:
* Android Studio emulator
* Android Studio -> ADB to Pixel 3a
* Install APK manually

However when installed from Play Store (uploaded bundle) it fails with this error.

Setting extractNativeLibs did not help
Tried variations on abiFilters including what's shown in this thread, did not help

Side note, one of the countless things I tried was to include sqlite as a dependency (importing latest sqlite aar compiled for Android). This did not resolve the problem.. however according to the Play Console it made the app MUCH more compatible with devices.

**Comment by connected-whunt** [comment]
Still an issue

**Comment by dimaslanjaka** [comment]
my working config 

```xml
<application
        android:name=".CoreApp"
        android:allowBackup="true"
        android:dataExtractionRules="@xml/data_extraction_rules"
        android:fullBackupContent="@xml/backup_rules"
        android:hardwareAccelerated="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:networkSecurityConfig="@xml/network_security_config"
        android:requestLegacyExternalStorage="true"
        android:supportsRtl="true"
        android:theme="@style/Theme.Reply.DayNight"
        android:extractNativeLibs="true"></application>
```

in gradle

```gradle
android {
    packagingOptions {
        jniLibs {
            useLegacyPackaging = true
        }
        merge "**/LICENSE.txt"
        merge "**/NOTICE.txt"
        exclude "**/*.ignore"
        exclude "**/*.ignored"
        // kotlin coroutines
        resources.excludes += "DebugProbesKt.bin"
        exclude("META-INF/DEPENDENCIES")
        exclude("META-INF/LICENSE")
        exclude("META-INF/license.txt")
        exclude("META-INF/NOTICE.txt")
        exclude("META-INF/notice.txt")
        exclude("META-INF/ASL2.0")
        exclude("META-INF/*.kotlin_module")
        exclude('mozilla/public-suffix-list.txt')
    }
}
```
